/**
 * 食材冷冻指南数据
 * 每条食材标注：是否可直接冻、处理方法、保质期限
 * 按六大分类组织
 */
export const FREEZING_CATEGORIES = [
  { key: 'meat',    label: '🥩 肉类',      emoji: '🥩' },
  { key: 'seafood', label: '🐟 海鲜',      emoji: '🐟' },
  { key: 'veggie',  label: '🥬 蔬菜',      emoji: '🥬' },
  { key: 'fruit',   label: '🍎 水果',      emoji: '🍎' },
  { key: 'egg_dairy', label: '🥚 蛋奶豆制品', emoji: '🥚' },
  { key: 'staple',  label: '🍞 主食半成品', emoji: '🍞' },
];

/**
 * @typedef {Object} FreezeItem
 * @property {string} id
 * @property {string} name - 食材名称
 * @property {string} category - 分类key
 * @property {boolean} directFreeze - true=可直接冻, false=需处理
 * @property {string} method - 处理方法
 * @property {string} shelfLife - 保质期限
 */

/** @type {FreezeItem[]} */
export const FREEZE_ITEMS = [
  // ═══════ 肉类 ═══════
  { id: 'meat_01', name: '猪/牛/羊肉（大块）', category: 'meat', directFreeze: true,
    method: '按一次用量切块，用厨房纸吸干表面水分，保鲜膜紧贴包裹再套密封袋，排尽空气',
    shelfLife: '3-6 个月' },
  { id: 'meat_02', name: '肉馅', category: 'meat', directFreeze: true,
    method: '按用量分装压扁（越薄解冻越快），密封袋平铺冷冻',
    shelfLife: '3 个月' },
  { id: 'meat_03', name: '鸡/鸭/整禽', category: 'meat', directFreeze: true,
    method: '去内脏、洗净沥干，整只或分切后密封',
    shelfLife: '6-12 个月' },
  { id: 'meat_04', name: '排骨/腔骨', category: 'meat', directFreeze: true,
    method: '洗净沥干，按份分装',
    shelfLife: '4-6 个月' },
  { id: 'meat_05', name: '培根/火腿片', category: 'meat', directFreeze: true,
    method: '原包装外面再套一层密封袋，用油纸隔层防粘连',
    shelfLife: '1-2 个月' },
  { id: 'meat_06', name: '腊肉/腊肠', category: 'meat', directFreeze: true,
    method: '已经风干脱水，直接密封袋冷冻',
    shelfLife: '6 个月以上' },
  { id: 'meat_07', name: '内脏（肝/腰/心）', category: 'meat', directFreeze: false,
    method: '洗净去膜去筋，切片或整块，焯水30秒过凉沥干再冻',
    shelfLife: '2-3 个月' },

  // ═══════ 海鲜 ═══════
  { id: 'sea_01', name: '整条鱼', category: 'seafood', directFreeze: false,
    method: '去鳞去鳃去内脏（不去内脏冻了会苦），洗净沥干，内膛塞姜片去腥，保鲜膜紧裹再密封袋',
    shelfLife: '3-6 个月' },
  { id: 'sea_02', name: '鱼片/鱼柳', category: 'seafood', directFreeze: true,
    method: '吸干水分，每片用保鲜膜单独包（防粘连），再装密封袋',
    shelfLife: '3 个月' },
  { id: 'sea_03', name: '虾', category: 'seafood', directFreeze: false,
    method: '去虾线！去头或留头随意，剪开后背挑虾线，沥干后平铺速冻（先单冻再装袋）',
    shelfLife: '3-4 个月' },
  { id: 'sea_04', name: '螃蟹/龙虾', category: 'seafood', directFreeze: false,
    method: '蒸熟再冻！生冻肉质会变空。蒸熟后凉透，保鲜膜包裹密封',
    shelfLife: '1 个月' },
  { id: 'sea_05', name: '贝类（蛤蜊/扇贝/蛏子）', category: 'seafood', directFreeze: false,
    method: '焯水取肉再冻。带壳生冻会腥臭且口感全毁。取肉后冷冻',
    shelfLife: '1-2 个月' },
  { id: 'sea_06', name: '鱿鱼/墨鱼/八爪鱼', category: 'seafood', directFreeze: false,
    method: '去内脏、去骨/去牙、去皮，洗净切圈或整只，吸干水分密封袋',
    shelfLife: '3 个月' },
  { id: 'sea_07', name: '三文鱼/金枪鱼（刺身级）', category: 'seafood', directFreeze: true,
    method: '原包装+密封袋，-18°C以下才能杀寄生虫（家庭冰箱3天起步）。口感会下降，生食建议鲜买',
    shelfLife: '1-2 个月（口感）' },
  { id: 'sea_08', name: '速冻虾仁/鱼丸', category: 'seafood', directFreeze: true,
    method: '原包装直接冻，开封后换密封袋',
    shelfLife: '3-6 个月' },

  // ═══════ 蔬菜 ═══════
  { id: 'veg_01', name: '西兰花/花菜', category: 'veggie', directFreeze: false,
    method: '焯水1-2分钟（加盐加油保色），捞出过冰水沥干，平铺速冻',
    shelfLife: '8 个月' },
  { id: 'veg_02', name: '菠菜/苋菜/叶菜', category: 'veggie', directFreeze: false,
    method: '沸水焯30秒→冰水→挤干水分→团成球再冻，做汤做馅直接扔',
    shelfLife: '6 个月' },
  { id: 'veg_03', name: '豆角/豇豆/四季豆', category: 'veggie', directFreeze: false,
    method: '掐头去筋，焯水3分钟，过凉沥干，切段冻',
    shelfLife: '6 个月' },
  { id: 'veg_04', name: '玉米', category: 'veggie', directFreeze: false,
    method: '带壳煮5分钟，捞出凉透，剥粒或整根包裹密封',
    shelfLife: '8-12 个月' },
  { id: 'veg_05', name: '豌豆/毛豆/蚕豆', category: 'veggie', directFreeze: false,
    method: '剥壳后焯水1分钟，过凉沥干速冻',
    shelfLife: '8 个月' },
  { id: 'veg_06', name: '胡萝卜/白萝卜', category: 'veggie', directFreeze: false,
    method: '切块/切丝焯水1分钟再冻，口感更好；或直接切好生冻（口感偏硬）',
    shelfLife: '6 个月' },
  { id: 'veg_07', name: '土豆', category: 'veggie', directFreeze: false,
    method: '生土豆冻了会变甜变黑水汪汪。蒸熟压成土豆泥再冻，或炸半熟做薯条冻',
    shelfLife: '3-6 个月（熟制）' },
  { id: 'veg_08', name: '南瓜/红薯/紫薯', category: 'veggie', directFreeze: false,
    method: '蒸熟压泥或切块蒸半熟再冻。生冻口感全毁',
    shelfLife: '6 个月' },
  { id: 'veg_09', name: '番茄', category: 'veggie', directFreeze: true,
    method: '整个洗净直接冻（冻完皮好剥，做菜直接扔锅里），但不适合凉拌了',
    shelfLife: '6 个月' },
  { id: 'veg_10', name: '洋葱/青椒/彩椒', category: 'veggie', directFreeze: false,
    method: '切丁/切丝直接冻（不用焯水），铺平速冻随用随取',
    shelfLife: '3 个月' },
  { id: 'veg_11', name: '葱/姜/蒜', category: 'veggie', directFreeze: false,
    method: '切碎末直接冻，用冰格分装最方便，随取随用',
    shelfLife: '3 个月' },
  { id: 'veg_12', name: '茄子', category: 'veggie', directFreeze: false,
    method: '切块蒸5分钟再冻，生冻会发苦',
    shelfLife: '4 个月' },
  { id: 'veg_13', name: '菌菇类（香菇/杏鲍菇/口蘑）', category: 'veggie', directFreeze: false,
    method: '切片干煸去水分（不放油）再冻，生冻出水变橡皮',
    shelfLife: '6 个月' },
  { id: 'veg_14', name: '秋葵', category: 'veggie', directFreeze: false,
    method: '整根焯水2分钟，过冰水沥干后整根冻',
    shelfLife: '6 个月' },
  { id: 'veg_15', name: '芦笋', category: 'veggie', directFreeze: false,
    method: '去老根，焯水1分钟，过凉沥干',
    shelfLife: '4 个月' },
  { id: 'veg_16', name: '莲藕', category: 'veggie', directFreeze: false,
    method: '去皮切片焯水2分钟，过凉沥干再冻',
    shelfLife: '4-6 个月' },

  // ═══════ 水果 ═══════
  { id: 'fruit_01', name: '香蕉', category: 'fruit', directFreeze: false,
    method: '去皮切段冻（冻完直接打奶昔），带皮冻会哭的',
    shelfLife: '3 个月' },
  { id: 'fruit_02', name: '草莓/蓝莓/树莓/桑葚', category: 'fruit', directFreeze: true,
    method: '洗净沥干（必须完全干！），铺平速冻，冻硬后装袋',
    shelfLife: '8-12 个月' },
  { id: 'fruit_03', name: '芒果/菠萝/木瓜', category: 'fruit', directFreeze: false,
    method: '去皮切块，铺平速冻后装袋',
    shelfLife: '6 个月' },
  { id: 'fruit_04', name: '桃子/李子/杏', category: 'fruit', directFreeze: false,
    method: '去皮切块，用柠檬水泡一下防氧化，密封冻',
    shelfLife: '4 个月' },
  { id: 'fruit_05', name: '葡萄', category: 'fruit', directFreeze: true,
    method: '洗净沥干直接冻，就是天然冰棒',
    shelfLife: '3 个月' },
  { id: 'fruit_06', name: '牛油果', category: 'fruit', directFreeze: false,
    method: '切半去核挖果肉，加柠檬汁压泥密封冻，整冻会发黑',
    shelfLife: '4 个月' },
  { id: 'fruit_07', name: '柠檬/青柠', category: 'fruit', directFreeze: false,
    method: '切片或挤汁冻（冰格冻汁最方便），整颗冻了难用',
    shelfLife: '3-4 个月' },
  { id: 'fruit_08', name: '榴莲', category: 'fruit', directFreeze: false,
    method: '去壳取肉密封冻，冻榴莲更香',
    shelfLife: '6-12 个月' },

  // ═══════ 蛋奶豆制品 ═══════
  { id: 'ed_01', name: '鸡蛋（整颗带壳）', category: 'egg_dairy', directFreeze: false,
    method: '壳会炸、蛋清变胶状。蛋液打散装冰格，或蛋黄蛋白分开冻',
    shelfLife: '3-6 个月（蛋液）' },
  { id: 'ed_02', name: '牛奶', category: 'egg_dairy', directFreeze: false,
    method: '直接冻会分层。打散摇匀后冰格冻，解冻后只能烹饪用（不能喝）',
    shelfLife: '1 个月' },
  { id: 'ed_03', name: '豆腐', category: 'egg_dairy', directFreeze: false,
    method: '切块焯水2分钟沥干再冻（冻豆腐就是冻出来的，孔洞吸汤汁神器！）',
    shelfLife: '3 个月' },
  { id: 'ed_04', name: '豆干/豆皮/腐竹', category: 'egg_dairy', directFreeze: true,
    method: '密封袋直接冻，口感基本不变',
    shelfLife: '3-6 个月' },
  { id: 'ed_05', name: '硬质奶酪（帕玛森/切达）', category: 'egg_dairy', directFreeze: true,
    method: '擦丝冻最好用，整块冻会碎。奶油奶酪/马斯卡彭不宜冻',
    shelfLife: '6 个月' },
  { id: 'ed_06', name: '黄油', category: 'egg_dairy', directFreeze: true,
    method: '原包装+密封袋',
    shelfLife: '6-12 个月' },
  { id: 'ed_07', name: '淡奶油（未打发）', category: 'egg_dairy', directFreeze: true,
    method: '倒入冰格冻成奶油块，解冻后只能用于烹饪/烘焙，不能打发',
    shelfLife: '2-3 个月' },
  { id: 'ed_08', name: '豆浆/豆奶', category: 'egg_dairy', directFreeze: true,
    method: '直接冻（冰格），解冻后摇匀饮用或烹饪',
    shelfLife: '1-2 个月' },

  // ═══════ 主食半成品 ═══════
  { id: 'staple_01', name: '米饭', category: 'staple', directFreeze: true,
    method: '煮好凉透，分装压平密封，微波炉叮2分钟跟新煮的一样',
    shelfLife: '1 个月' },
  { id: 'staple_02', name: '馒头/包子/花卷', category: 'staple', directFreeze: false,
    method: '蒸熟放凉再冻（生冻会塌），密封袋排空气',
    shelfLife: '1-2 个月' },
  { id: 'staple_03', name: '饺子/馄饨', category: 'staple', directFreeze: false,
    method: '包好生冻！铺平速冻，冻硬了再装袋（防粘连）',
    shelfLife: '3 个月' },
  { id: 'staple_04', name: '手抓饼/葱油饼/春卷皮', category: 'staple', directFreeze: true,
    method: '每层用油纸隔开，密封袋',
    shelfLife: '6-12 个月' },
  { id: 'staple_05', name: '鲜面条/湿面', category: 'staple', directFreeze: false,
    method: '分团撒干粉卷好冻，不然会粘成一坨',
    shelfLife: '1 个月' },
  { id: 'staple_06', name: '面包/吐司', category: 'staple', directFreeze: true,
    method: '切片后密封冻（不要冷藏，冷藏加速淀粉老化），吃的时候直接烤或蒸',
    shelfLife: '1 个月' },
  { id: 'staple_07', name: '披萨', category: 'staple', directFreeze: false,
    method: '烤至8成熟再冻，生冻饼底会湿',
    shelfLife: '2 个月' },
  { id: 'staple_08', name: '粽子/烧麦/糯米鸡', category: 'staple', directFreeze: false,
    method: '蒸熟放凉，单个包裹密封冻',
    shelfLife: '2-3 个月' },
  { id: 'staple_09', name: '油条/炸物半成品', category: 'staple', directFreeze: true,
    method: '炸好凉透密封冻，吃的时候空气炸锅复热',
    shelfLife: '1 个月' },
];

/** 按分类获取食材列表 */
export function getItemsByCategory(categoryKey) {
  if (!categoryKey) return FREEZE_ITEMS;
  return FREEZE_ITEMS.filter(item => item.category === categoryKey);
}
